### ISSUE TITLE
stratc --aws option can't make forward progress if it fails the first time. 

### ISSUE THREAD

**Issue by chriskiehl** [litlang/lit#11]
```
$ stratc --aws ./HelloWorld.sa
Creating role 1515fb025939d8ef-HelloWorld-strat_generated_proxy_Http
Creating role 1515fb025939d8ef-HelloWorld-strat_generated_proxy_HttpHttp
Internal stratc failure:
EntityAlreadyExists: Role with name 1515fb025939d8ef-HelloWorld-strat_generated_proxy_HttpHttp already exists.
```

First deploy encountered a failure due to Lambda permissions. I cannot make forward progress after fixing my permission issues unless I go in and manually clean up the roles in the IAM Console.

**Comment by CaptainCharlieGreen** [comment]
If you rebuild the sa file it gets a new ID and can deploy again--very bad solution but it does work...

The AWS SDK is rarely idempotent and I bailed on trying to make stratc idempotent because of the headache around wrapping everything.  Its probably worth making it idempotent for mvp though : /
