### ISSUE TITLE
Books guide could use more contextual code samples 

### ISSUE THREAD

**Issue by chriskiehl** [litlang/lit#13]
Got stuck for about 5 min unable to get past the `cloud not resolve Sales.getSales` section because I misread the "include "Http" at the top of FrontendProxy" line of the guide to mean "goes at the top", like a dummy. 

A "your code now looks like this" checkin point could help other dumb people like myself. 

```
service Books {
   include 'http://url.example.com'  <-- LOOK HERE
}
```

**Comment by CaptainCharlieGreen** [comment]
👍

**Comment by CaptainCharlieGreen** [comment]
https://strat.world/Guides/Bookstore
