### ISSUE TITLE
Doc pages appear to be written directly in HTML 

### ISSUE THREAD

**Issue by chriskiehl** [litlang/lit#5]
Hello Captain,

Spent time searching for .md files against which I could submit doc fixes. Found none. Only HTML. Contribution requirements unclear. Are these html files human edited, and thus safe to submit PRs against, or are they generated output? 

Example: https://github.com/litlang/lit/blob/master/docs/Guides/Hello%20World.html

**Comment by ChaliceG** [comment]
https://github.com/litlang/lit/blob/master/docsSrc/markdown/Guides/Hello%20World.md

run 

$ node docsSrc/docGenRoot.js

to compile docs

https://github.com/litlang/lit/blob/master/docsSrc/docsGenRoot.js
