### ISSUE TITLE
nit: guides are in reverse complixity order

### ISSUE THREAD

**Issue by chriskiehl** [litlang/lit#9]
Guides section starts with `Advanced Stuff!` and moves eventually into `HelloWorld`. Maybe flip those around for less scary introductions. 

https://github.com/stratworld/strat/blob/f138b8e92813ab54c578f74d34168214baffeee3/docs/Sources/Cron.html#L27

**Comment by CaptainCharlieGreen** [comment]
They're in alphabetical order : /

I see your point; could implement a hack here:

https://github.com/stratworld/strat/blob/master/docsSrc/docsGenRoot.js#L89
